#
# simple-log
# Very simple loging library.
#
# Copyright ©2023 Marcin Orlowski <mail [@] MarcinOrlowski.com>
# https://github.com/MarcinOrlowski/python-simple-log/
#

name: "Unit tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  unittests:
    name: "Testing"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ ubuntu-latest ]
        python: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed files..."
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            srcs:
              - '**/*.py'

      - name: "Setup Python"
        if: steps.filter.outputs.srcs == 'true'
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      - name: "Running unit tests..."
        if: steps.filter.outputs.srcs == 'true'
        run: python -m unittest discover tests
